name: Build and Deploy user microservice to Development

on:
  push:
    branches-ignore:
      - main    

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/microservices-nodejs.yaml@main
    with:
      MICROSERVICE: user
      IMAGE: user
      NAMESPACE: user-microservice
      RELEASE: user
      WORKING_DIR: ./user
      DOCKERFILE_PATH: ./user
    secrets: inherit